name: flutter_update_checker_plus
description: Based on flutter_update_checker to check update for Android (Google Play, App Gallery, RuStore) and iOS (AppStore)
version: 0.0.5
homepage: https://github.com/bousalem98/flutter_update_checker_plus
repository: https://github.com/bousalem98/flutter_update_checker_plus
issue_tracker: https://github.com/bousalem98/flutter_update_checker_plus/issues

screenshots:
  - description: "flutter_update_checker_plus Logo"
    path: other/docs/images/pub_logo.png

topics:
  - update

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  in_app_update: ^4.2.5
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

platforms:
  android:
  ios:
